'use client';

import { useState } from 'react';
import { FieldConfig, LeadData } from '@/lib/types';
import { LeadForm } from '@/components/lead-form';
import { LeadDisplay } from '@/components/lead-display';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useToast } from '@/hooks/use-toast';

// Lead schema from the provided JSON
const LEAD_SCHEMA: FieldConfig[] = [
  {
    genListColId: 2001,
    genListId: 1001,
    columnName: 'lead_id',
    displayName: 'Lead ID',
    dataType: 'NUMBER',
    dbDataType: 'BIGINT',
    dbLength: null,
    dbPrecision: null,
    dbScale: null,
    displayOrder: 1,
    placeholderText: '',
    helpText: 'System-generated unique ID',
    required: true,
    defaultValue: null,
    minValue: null,
    maxValue: null,
    regexPattern: null,
    regexMessage: null,
    lovCode: null,
    customValidationExpr: null,
    validationErrorMessage: null,
    editable: false,
    visible: true,
    searchable: true,
    sortable: true,
    unique: false,
    indexed: false,
    createdBy: 'SYSTEM',
    createdDate: '2026-02-04T08:34:59.459715',
    updatedBy: 'SYSTEM',
    updatedDate: '2026-02-04T08:34:59.459715',
  },
  {
    genListColId: 2002,
    genListId: 1001,
    columnName: 'lead_source',
    displayName: 'Lead Source',
    dataType: 'DROPDOWN',
    dbDataType: 'VARCHAR',
    dbLength: 100,
    dbPrecision: null,
    dbScale: null,
    displayOrder: 2,
    placeholderText: '',
    helpText: 'Website, Referral, Agent, Cold Call',
    required: true,
    defaultValue: null,
    minValue: null,
    maxValue: null,
    regexPattern: null,
    regexMessage: null,
    lovCode: 'LEAD_SOURCE_LOV',
    customValidationExpr: null,
    validationErrorMessage: null,
    editable: true,
    visible: true,
    searchable: true,
    sortable: true,
    unique: false,
    indexed: false,
    createdBy: 'SYSTEM',
    createdDate: '2026-02-04T08:34:59.459715',
    updatedBy: 'SYSTEM',
    updatedDate: '2026-02-04T08:34:59.459715',
  },
  {
    genListColId: 2003,
    genListId: 1001,
    columnName: 'campaign_referral_name',
    displayName: 'Campaign / Referral Name',
    dataType: 'TEXT',
    dbDataType: 'VARCHAR',
    dbLength: 150,
    dbPrecision: null,
    dbScale: null,
    displayOrder: 3,
    placeholderText: '',
    helpText: 'Marketing or referral identifier',
    required: false,
    defaultValue: null,
    minValue: null,
    maxValue: null,
    regexPattern: null,
    regexMessage: null,
    lovCode: null,
    customValidationExpr: null,
    validationErrorMessage: null,
    editable: true,
    visible: true,
    searchable: true,
    sortable: true,
    unique: false,
    indexed: false,
    createdBy: 'SYSTEM',
    createdDate: '2026-02-04T08:34:59.459715',
    updatedBy: 'SYSTEM',
    updatedDate: '2026-02-04T08:34:59.459715',
  },
  {
    genListColId: 2004,
    genListId: 1001,
    columnName: 'company_name',
    displayName: 'Company Name',
    dataType: 'TEXT',
    dbDataType: 'VARCHAR',
    dbLength: 150,
    dbPrecision: null,
    dbScale: null,
    displayOrder: 4,
    placeholderText: '',
    helpText: 'Exporter / Importer / Shipper',
    required: true,
    defaultValue: null,
    minValue: null,
    maxValue: null,
    regexPattern: null,
    regexMessage: null,
    lovCode: null,
    customValidationExpr: null,
    validationErrorMessage: null,
    editable: true,
    visible: true,
    searchable: true,
    sortable: true,
    unique: false,
    indexed: false,
    createdBy: 'SYSTEM',
    createdDate: '2026-02-04T08:34:59.459715',
    updatedBy: 'SYSTEM',
    updatedDate: '2026-02-04T08:34:59.459715',
  },
  {
    genListColId: 2005,
    genListId: 1001,
    columnName: 'primary_contact_name',
    displayName: 'Primary Contact Name',
    dataType: 'TEXT',
    dbDataType: 'VARCHAR',
    dbLength: 150,
    dbPrecision: null,
    dbScale: null,
    displayOrder: 5,
    placeholderText: '',
    helpText: 'Decision maker',
    required: true,
    defaultValue: null,
    minValue: null,
    maxValue: null,
    regexPattern: null,
    regexMessage: null,
    lovCode: null,
    customValidationExpr: null,
    validationErrorMessage: null,
    editable: true,
    visible: true,
    searchable: true,
    sortable: true,
    unique: false,
    indexed: false,
    createdBy: 'SYSTEM',
    createdDate: '2026-02-04T08:34:59.459715',
    updatedBy: 'SYSTEM',
    updatedDate: '2026-02-04T08:34:59.459715',
  },
  {
    genListColId: 2006,
    genListId: 1001,
    columnName: 'email',
    displayName: 'Email',
    dataType: 'EMAIL',
    dbDataType: 'VARCHAR',
    dbLength: 150,
    dbPrecision: null,
    dbScale: null,
    displayOrder: 6,
    placeholderText: '',
    helpText: '',
    required: true,
    defaultValue: null,
    minValue: null,
    maxValue: null,
    regexPattern: null,
    regexMessage: null,
    lovCode: null,
    customValidationExpr: null,
    validationErrorMessage: null,
    editable: true,
    visible: true,
    searchable: true,
    sortable: true,
    unique: false,
    indexed: false,
    createdBy: 'SYSTEM',
    createdDate: '2026-02-04T08:34:59.459715',
    updatedBy: 'SYSTEM',
    updatedDate: '2026-02-04T08:34:59.459715',
  },
  {
    genListColId: 2007,
    genListId: 1001,
    columnName: 'phone',
    displayName: 'Phone',
    dataType: 'PHONE',
    dbDataType: 'VARCHAR',
    dbLength: 30,
    dbPrecision: null,
    dbScale: null,
    displayOrder: 7,
    placeholderText: '',
    helpText: '',
    required: true,
    defaultValue: null,
    minValue: null,
    maxValue: null,
    regexPattern: null,
    regexMessage: null,
    lovCode: null,
    customValidationExpr: null,
    validationErrorMessage: null,
    editable: true,
    visible: true,
    searchable: true,
    sortable: true,
    unique: false,
    indexed: false,
    createdBy: 'SYSTEM',
    createdDate: '2026-02-04T08:34:59.459715',
    updatedBy: 'SYSTEM',
    updatedDate: '2026-02-04T08:34:59.459715',
  },
  {
    genListColId: 2008,
    genListId: 1001,
    columnName: 'country',
    displayName: 'Country',
    dataType: 'DROPDOWN',
    dbDataType: 'VARCHAR',
    dbLength: 100,
    dbPrecision: null,
    dbScale: null,
    displayOrder: 8,
    placeholderText: '',
    helpText: '',
    required: true,
    defaultValue: null,
    minValue: null,
    maxValue: null,
    regexPattern: null,
    regexMessage: null,
    lovCode: 'COUNTRY_LOV',
    customValidationExpr: null,
    validationErrorMessage: null,
    editable: true,
    visible: true,
    searchable: true,
    sortable: true,
    unique: false,
    indexed: false,
    createdBy: 'SYSTEM',
    createdDate: '2026-02-04T08:34:59.459715',
    updatedBy: 'SYSTEM',
    updatedDate: '2026-02-04T08:34:59.459715',
  },
  {
    genListColId: 2009,
    genListId: 1001,
    columnName: 'city',
    displayName: 'City',
    dataType: 'TEXT',
    dbDataType: 'VARCHAR',
    dbLength: 150,
    dbPrecision: null,
    dbScale: null,
    displayOrder: 9,
    placeholderText: '',
    helpText: '',
    required: true,
    defaultValue: null,
    minValue: null,
    maxValue: null,
    regexPattern: null,
    regexMessage: null,
    lovCode: null,
    customValidationExpr: null,
    validationErrorMessage: null,
    editable: true,
    visible: true,
    searchable: true,
    sortable: true,
    unique: false,
    indexed: false,
    createdBy: 'SYSTEM',
    createdDate: '2026-02-04T08:34:59.459715',
    updatedBy: 'SYSTEM',
    updatedDate: '2026-02-04T08:34:59.459715',
  },
  {
    genListColId: 2010,
    genListId: 1001,
    columnName: 'service_line_interested',
    displayName: 'Service Line Interested',
    dataType: 'MULTISELECT',
    dbDataType: 'VARCHAR',
    dbLength: 200,
    dbPrecision: null,
    dbScale: null,
    displayOrder: 10,
    placeholderText: '',
    helpText: 'Freight Forwarding, Transportation, 3PL',
    required: true,
    defaultValue: null,
    minValue: null,
    maxValue: null,
    regexPattern: null,
    regexMessage: null,
    lovCode: 'SERVICE_LINE_INTERESTED_LOV',
    customValidationExpr: null,
    validationErrorMessage: null,
    editable: true,
    visible: true,
    searchable: true,
    sortable: true,
    unique: false,
    indexed: false,
    createdBy: 'SYSTEM',
    createdDate: '2026-02-04T08:34:59.459715',
    updatedBy: 'SYSTEM',
    updatedDate: '2026-02-04T08:34:59.459715',
  },
  {
    genListColId: 2011,
    genListId: 1001,
    columnName: 'estimated_monthly_volume',
    displayName: 'Estimated Monthly Volume',
    dataType: 'NUMBER',
    dbDataType: 'NUMERIC',
    dbLength: null,
    dbPrecision: 18,
    dbScale: 2,
    displayOrder: 11,
    placeholderText: '',
    helpText: 'High-level volume',
    required: false,
    defaultValue: null,
    minValue: null,
    maxValue: null,
    regexPattern: null,
    regexMessage: null,
    lovCode: null,
    customValidationExpr: null,
    validationErrorMessage: null,
    editable: true,
    visible: true,
    searchable: true,
    sortable: true,
    unique: false,
    indexed: false,
    createdBy: 'SYSTEM',
    createdDate: '2026-02-04T08:34:59.459715',
    updatedBy: 'SYSTEM',
    updatedDate: '2026-02-04T08:34:59.459715',
  },
  {
    genListColId: 2012,
    genListId: 1001,
    columnName: 'expected_start_date',
    displayName: 'Expected Start Date',
    dataType: 'DATE',
    dbDataType: 'DATE',
    dbLength: null,
    dbPrecision: null,
    dbScale: null,
    displayOrder: 12,
    placeholderText: '',
    helpText: '',
    required: false,
    defaultValue: null,
    minValue: null,
    maxValue: null,
    regexPattern: null,
    regexMessage: null,
    lovCode: null,
    customValidationExpr: null,
    validationErrorMessage: null,
    editable: true,
    visible: true,
    searchable: true,
    sortable: true,
    unique: false,
    indexed: false,
    createdBy: 'SYSTEM',
    createdDate: '2026-02-04T08:34:59.459715',
    updatedBy: 'SYSTEM',
    updatedDate: '2026-02-04T08:34:59.459715',
  },
  {
    genListColId: 2013,
    genListId: 1001,
    columnName: 'lead_status',
    displayName: 'Lead Status',
    dataType: 'DROPDOWN',
    dbDataType: 'VARCHAR',
    dbLength: 100,
    dbPrecision: null,
    dbScale: null,
    displayOrder: 13,
    placeholderText: '',
    helpText: 'New, Contacted, Qualified, Disqualified',
    required: true,
    defaultValue: null,
    minValue: null,
    maxValue: null,
    regexPattern: null,
    regexMessage: null,
    lovCode: 'LEAD_STATUS_LOV',
    customValidationExpr: null,
    validationErrorMessage: null,
    editable: true,
    visible: true,
    searchable: true,
    sortable: true,
    unique: false,
    indexed: false,
    createdBy: 'SYSTEM',
    createdDate: '2026-02-04T08:34:59.459715',
    updatedBy: 'SYSTEM',
    updatedDate: '2026-02-04T08:34:59.459715',
  },
  {
    genListColId: 2014,
    genListId: 1001,
    columnName: 'assigned_sales_rep',
    displayName: 'Assigned Sales Rep',
    dataType: 'USER',
    dbDataType: 'VARCHAR',
    dbLength: 100,
    dbPrecision: null,
    dbScale: null,
    displayOrder: 14,
    placeholderText: '',
    helpText: '',
    required: true,
    defaultValue: null,
    minValue: null,
    maxValue: null,
    regexPattern: null,
    regexMessage: null,
    lovCode: null,
    customValidationExpr: null,
    validationErrorMessage: null,
    editable: true,
    visible: true,
    searchable: true,
    sortable: true,
    unique: false,
    indexed: false,
    createdBy: 'SYSTEM',
    createdDate: '2026-02-04T08:34:59.459715',
    updatedBy: 'SYSTEM',
    updatedDate: '2026-02-04T08:34:59.459715',
  },
  {
    genListColId: 2015,
    genListId: 1001,
    columnName: 'notes',
    displayName: 'Notes',
    dataType: 'TEXTAREA',
    dbDataType: 'VARCHAR',
    dbLength: 500,
    dbPrecision: null,
    dbScale: null,
    displayOrder: 15,
    placeholderText: '',
    helpText: 'Free-text',
    required: false,
    defaultValue: null,
    minValue: null,
    maxValue: null,
    regexPattern: null,
    regexMessage: null,
    lovCode: null,
    customValidationExpr: null,
    validationErrorMessage: null,
    editable: true,
    visible: true,
    searchable: true,
    sortable: true,
    unique: false,
    indexed: false,
    createdBy: 'SYSTEM',
    createdDate: '2026-02-04T08:34:59.459715',
    updatedBy: 'SYSTEM',
    updatedDate: '2026-02-04T08:34:59.459715',
  },
];

// Sample lead data for display
const SAMPLE_LEAD: LeadData = {
  lead_id: 1001,
  lead_source: 'REFERRAL',
  campaign_referral_name: 'Partner Network Q1 2026',
  company_name: 'Global Logistics Inc',
  primary_contact_name: 'Sarah Johnson',
  email: 'sarah.johnson@globallogistics.com',
  phone: '+1 (415) 555-0123',
  country: 'US',
  city: 'San Francisco',
  service_line_interested: ['FREIGHT_FORWARDING', '3PL'],
  estimated_monthly_volume: 5000.00,
  expected_start_date: '2026-03-15',
  lead_status: 'QUALIFIED',
  assigned_sales_rep: 'John Smith',
  notes: 'High-priority lead. Large volume potential. Decision maker is very interested in freight forwarding services. Follow up scheduled for next week.',
};

export default function Home() {
  const [activeTab, setActiveTab] = useState('form');
  const [formData, setFormData] = useState<LeadData>(SAMPLE_LEAD);
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const handleFormSubmit = async (data: LeadData) => {
    setIsLoading(true);
    try {
      // Simulate API call
      await new Promise((resolve) => setTimeout(resolve, 1000));
      setFormData(data);
      setActiveTab('display');
      toast({
        title: 'Success',
        description: 'Lead information saved successfully',
      });
    } catch (error) {
      toast({
        title: 'Error',
        description: 'Failed to save lead information',
        variant: 'destructive',
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <main className="min-h-screen bg-gray-50 py-12">
      <div className="mx-auto max-w-4xl px-4">
        <div className="mb-8">
          <h1 className="mb-2 text-3xl font-bold text-gray-900">Lead Management CRM</h1>
          <p className="text-gray-600">
            Dynamic form and display components built from your lead schema
          </p>
        </div>

        <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="form">Create / Edit Lead</TabsTrigger>
            <TabsTrigger value="display">View Lead Details</TabsTrigger>
          </TabsList>

          <TabsContent value="form" className="mt-6">
            <LeadForm
              fields={LEAD_SCHEMA}
              initialData={formData}
              onSubmit={handleFormSubmit}
              isLoading={isLoading}
            />
          </TabsContent>

          <TabsContent value="display" className="mt-6">
            <LeadDisplay fields={LEAD_SCHEMA} data={formData} />
          </TabsContent>
        </Tabs>
      </div>
    </main>
  );
}
